package hse.thesis.eusuilang.expression.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int BinaryMathExpression = 0;
  public static final int ElementType = 1;
  public static final int LogicalExpression = 2;
  public static final int MathAssigment = 3;
  public static final int MathBooleanType = 4;
  public static final int MathExpression = 5;
  public static final int MathType = 6;
  public static final int MathVarDeclaration = 7;
  public static final int MathVarReference = 8;
  public static final int NumberType = 9;
  public static final int UnaryMathExpression = 10;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x803eb20bd0744b77L, 0xa6bafeb2b2f284caL);
    builder.put(0x2f9345ae68201ff4L, BinaryMathExpression);
    builder.put(0x2f9345ae68208cb1L, ElementType);
    builder.put(0x2f9345ae68202395L, LogicalExpression);
    builder.put(0x2f9345ae681eb24dL, MathAssigment);
    builder.put(0x2f9345ae68202892L, MathBooleanType);
    builder.put(0x2f9345ae681e098bL, MathExpression);
    builder.put(0x2f9345ae68202893L, MathType);
    builder.put(0x2f9345ae681eb24fL, MathVarDeclaration);
    builder.put(0x2f9345ae681eb24eL, MathVarReference);
    builder.put(0x2f9345ae6820df46L, NumberType);
    builder.put(0x2f9345ae6827c701L, UnaryMathExpression);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
