package hse.thesis.esuilang.statemachine.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (index_xbvbvu_a0a.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Event_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new State_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new StateMachine_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Transition_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex index_xbvbvu_a0a = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xdc7dd0dec80e470fL, 0x841f58d89366c470L, 0x6dbfbf90a6a70ca2L), MetaIdFactory.conceptId(0xdc7dd0dec80e470fL, 0x841f58d89366c470L, 0x6dbfbf90a6a70ca3L), MetaIdFactory.conceptId(0xdc7dd0dec80e470fL, 0x841f58d89366c470L, 0x6dbfbf90a6a70be4L), MetaIdFactory.conceptId(0xdc7dd0dec80e470fL, 0x841f58d89366c470L, 0x6dbfbf90a6a7da3fL)).seal();
}
